routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'short', 'body',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    public function index() {
        $products = Product::orderBy('id', 'DESC')->paginate();
        return view('products.index', compact('products'));
    }

    public function create() {
        return view('products.create');
    }

    public function store(ProductRequest $request) {
        $product = new Product;

        $product->name  = $request->name;
        $product->short = $request->short;
        $product->body  = $request->body;

        $product->save();

        return redirect()->route('products.index')
                        ->with('info', 'El producto ha sido guardado');
    }

    public function edit($id) {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }

    public function update(ProductRequest $request, $id) {
        $product = Product::find($id);
        $product->name  = $request->name;
        $product->short = $request->short;
        $product->body  = $request->body;

        $product->save();

        return redirect()->route('products.index')
                        ->with('info', 'El producto fue actualizado');
    }

    public function show($id) {
        $product = Product::find($id);
        return view('products.show', compact('product'));
    }

    public function destroy($id) {
        $product = Product::find($id);
        $product->delete();

        return back()->with('info', 'El producto fue eliminado');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>App | DNeyser</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="page-header text-center">CRUD Laravel</h1>
            </div>
        </div>
        <div class="row">
            @yield('content')
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/products/create.blade.php
@extends('layout')

@section('content')
    <div class="col-sm-8">
        <h2>
            Nuevo producto
            <a href="{{ route('products.index') }}" class="btn btn-default pull-right">Listado</a>
        </h2>
        @include('products.fragment.error')
        {!! Form::open(['route' => 'products.store']) !!}

            @include('products.fragment.form')
        
        {!! Form::close() !!}
    </div>
    <div class="col-sm-4">
        @include('products.fragment.aside')
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layout')

@section('content')
    <div class="col-sm-8">
        <h2>
            Editar producto
            <a href="{{ route('products.index') }}" class="btn btn-default pull-right">Listado</a>
        </h2>
        @include('products.fragment.error')
        {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'PUT']) !!}

            @include('products.fragment.form')
        
        {!! Form::close() !!}
    </div>
    <div class="col-sm-4">
        @include('products.fragment.aside')
    </div>
@endsection

resources/views/products/fragment/aside.blade.php
<p class="alert alert-info">
    Desde aquí podemos crear, listar y eliminar los productos
</p>

resources/views/products/fragment/error.blade.php
@if(count($errors))
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">
            &times;
        </button>
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/products/fragment/form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Nombre del producto') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('short', 'Descripción breve del producto') !!}
    {!! Form::text('short', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('body', 'Descripción del producto') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
        {!! Form::submit('ENVIAR', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/products/fragment/info.blade.php
@if(Session::has('info'))
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">
            &times;
        </button>
        {{ Session::get('info') }}
    </div>
@endif

resources/views/products/index.blade.php
@extends('layout')

@section('content')
    <div class="col-sm-8">
        <h2>
            Listado de productos
            <a href="{{ route('products.create') }}" class="btn btn-primary pull-right">Nuevo</a>
        </h2>
        @include('products.fragment.info')
        <table class="table table-striped">
            <thead>
                <tr>
                    <th width="20px">ID</th>
                    <th>Nombre del producto</th>
                    <th colspan="3">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td>
                        <strong>{{ $product->name }}</strong>
                        {{ $product->short }}
                    </td>
                    <td>
                        <a href="{{ route('products.show', $product->id) }}" class="btn btn-link">Ver</a>
                    </td>
                    <td>
                        <a href="{{ route('products.edit', $product->id) }}" class="btn btn-link">Editar</a>
                    </td>
                    <td>
                        <form action="{{ route('products.destroy', $product->id)}}" method="POST">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">
                            <button class="btn btn-link">Borrar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {!! $products->render() !!}
    </div>
    <div class="col-sm-4">
        @include('products.fragment.aside')
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layout')

@section('content')
    <div class="col-sm-8">
        <h2>
            {{ $product->name }}
            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-default pull-right">Editar</a>
        </h2>
        <p>
            {{ $product->short }}
        </p>
        {!! $product->body !!}
    </div>
    <div class="col-sm-4">
        @include('products.fragment.aside')
    </div>
@endsection